### ISSUE TITLE
Replace All doesn't work with tables present

### ISSUE THREAD

**Issue by dgAmp** [DesModder/DesModder#548]
Replace All will not work if there is a table in the graph.

**Comment by jared-hughes** [comment]
Specific reproduction: https://www.desmos.com/calculator/zotcvksv0b. Try to find-replace `f(x)` with `x`. Then error

```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at script.js:5105:35
    at Array.forEach (<anonymous>)
    at script.js:5099:22
    at Array.forEach (<anonymous>)
    at replace (script.js:5080:28)
    at refactor (script.js:5213:7)
    at Controller2.refactorAll (script.js:5232:7)
```
