### ISSUE TITLE
Image with angle breaks Text Mode

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#552]
Modifying the value of an image's angle in Text Mode leads to the following error:

```
Uncaught Error: Expected valid itemAug in modify
    at itemChange (modify.ts:151:28)
    at eventSequenceChanges (modify.ts:96:10)
    at LanguageServer.processQueuedEvents (LanguageServer.ts:165:21)
    at LanguageServer.onCalcEvent (LanguageServer.ts:112:12)
    at Controller.ts:68:38
```

**Comment by jared-hughes** [comment]
Fixed by #564
