### ISSUE TITLE
Number field setting "Failed to execute 'removeChild' on 'Node'"

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#750]
1. Open "Compact View" settings
2. Edit "Math Font Size" from 18 to 17 by clicking in the number field, then typing backspace then "7"
3. Click on the graphpaper
4. Error in console:

```
VM1487:39 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at e.overrideChildUpdates (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:39:10384)
    at e.yH [as update] (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:38:5030)
    at e.yH [as update] (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:38:5113)
    at e.yH [as update] (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:38:5113)
    at e.overrideChildUpdates (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:39:10220)
    at e.yH [as update] (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:38:5030)
    at e.yH [as update] (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:38:5113)
    at PillboxContainer.yH [as update] (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:38:5113)
    at e.yH [as update] (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:38:5113)
    at e.overrideChildUpdates (eval at load (chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/preload/script.js:3387:14), <anonymous>:39:10220)
```

This also happens for other number fields, and in other plugins like multiline.

**Comment by radian628** [comment]
Just tested on Firefox (in a new branch freshly merged from upstream/main. I made sure to remove and add the plugin again in case FF is doing some stupid caching nonsense). Can't get this error to appear.

**Comment by radian628** [comment]
Can't replicate in Edge (chromium) either.

**Comment by radian628** [comment]
To account for the fact that this might be only in prod, I've checked with the latest release version from the extension store in both Edge and Firefox. I can't get the bug to happen in either.

**Comment by jared-hughes** [comment]
I've updated the instructions, in particular adding step 3 and clarifying that step 2 requires typing.

**Comment by radian628** [comment]
Alright, now I can replicate it lol. On my system it seems to specifically affect Edge (and likely by extension other Chromium browsers). Firefox is unaffected.

**Comment by jared-hughes** [comment]
I can no longer replicate this (Chrome)
